/* KẾ HOẠCH CHUẨN THEO SÁCH GIÁO VIÊN (Kết nối tri thức) — sinh bởi _lam-khgd-sgv.js, ĐỪNG sửa tay.
   Mốc trung lập cho mọi trường: số tiết từng bài lấy từ mục lục SGV, dồn theo số tiết/tuần
   của chương trình. Kế hoạch của tổ Quảng Châu 1 (khgd-lopN.js) chỉ là một biến thể.
   Khuôn 8 cột giống KHGD: [Tuần, Chủ đề, "", "", "Bài N. Tên (Tiết k)", "n tiết", Tiết KH, ""]. */
window.BX_KHGD_SGV = window.BX_KHGD_SGV || {};
window.BX_KHGD_SGV["3"] = window.BX_KHGD_SGV["3"] || {};
window.BX_KHGD_SGV["3"]["Toán"] = [
["1","Chủ đề 1: Ôn tập và bổ sung","","","Bài 1. Ôn tập các số đến 1 000 (Tiết 1)","2 tiết","1",""],
["1","Chủ đề 1: Ôn tập và bổ sung","","","Bài 1. Ôn tập các số đến 1 000 (Tiết 2)","","2",""],
["1","Chủ đề 1: Ôn tập và bổ sung","","","Bài 2. Ôn tập phép cộng, phép trừ trong phạm vi 1 000 (Tiết 1)","2 tiết","3",""],
["1","Chủ đề 1: Ôn tập và bổ sung","","","Bài 2. Ôn tập phép cộng, phép trừ trong phạm vi 1 000 (Tiết 2)","","4",""],
["1","Chủ đề 1: Ôn tập và bổ sung","","","Bài 3. Tìm thành phần trong phép cộng, phép trừ (Tiết 1)","2 tiết","5",""],
["2","Chủ đề 1: Ôn tập và bổ sung","","","Bài 3. Tìm thành phần trong phép cộng, phép trừ (Tiết 2)","","6",""],
["2","Chủ đề 1: Ôn tập và bổ sung","","","Bài 4. Ôn tập bảng nhân 2; 5, bảng chia 2; 5 (Tiết 1)","2 tiết","7",""],
["2","Chủ đề 1: Ôn tập và bổ sung","","","Bài 4. Ôn tập bảng nhân 2; 5, bảng chia 2; 5 (Tiết 2)","","8",""],
["2","Chủ đề 1: Ôn tập và bổ sung","","","Bài 5. Bảng nhân 3, bảng chia 3 (Tiết 1)","2 tiết","9",""],
["2","Chủ đề 1: Ôn tập và bổ sung","","","Bài 5. Bảng nhân 3, bảng chia 3 (Tiết 2)","","10",""],
["3","Chủ đề 1: Ôn tập và bổ sung","","","Bài 6. Bảng nhân 4, bảng chia 4 (Tiết 1)","2 tiết","11",""],
["3","Chủ đề 1: Ôn tập và bổ sung","","","Bài 6. Bảng nhân 4, bảng chia 4 (Tiết 2)","","12",""],
["3","Chủ đề 1: Ôn tập và bổ sung","","","Bài 7. Ôn tập hình học và đo lường (Tiết 1)","2 tiết","13",""],
["3","Chủ đề 1: Ôn tập và bổ sung","","","Bài 7. Ôn tập hình học và đo lường (Tiết 2)","","14",""],
["3","Chủ đề 1: Ôn tập và bổ sung","","","Bài 8. Luyện tập chung (Tiết 1)","2 tiết","15",""],
["4","Chủ đề 1: Ôn tập và bổ sung","","","Bài 8. Luyện tập chung (Tiết 2)","","16",""],
["4","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 9. Bảng nhân 6, bảng chia 6 (Tiết 1)","2 tiết","17",""],
["4","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 9. Bảng nhân 6, bảng chia 6 (Tiết 2)","","18",""],
["4","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 10. Bảng nhân 7, bảng chia 7 (Tiết 1)","2 tiết","19",""],
["4","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 10. Bảng nhân 7, bảng chia 7 (Tiết 2)","","20",""],
["5","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 11. Bảng nhân 8, bảng chia 8 (Tiết 1)","2 tiết","21",""],
["5","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 11. Bảng nhân 8, bảng chia 8 (Tiết 2)","","22",""],
["5","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 12. Bảng nhân 9, bảng chia 9 (Tiết 1)","2 tiết","23",""],
["5","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 12. Bảng nhân 9, bảng chia 9 (Tiết 2)","","24",""],
["5","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 13. Tìm thành phần trong phép nhân, phép chia (Tiết 1)","2 tiết","25",""],
["6","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 13. Tìm thành phần trong phép nhân, phép chia (Tiết 2)","","26",""],
["6","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 14. Một phần mấy (Tiết 1)","2 tiết","27",""],
["6","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 14. Một phần mấy (Tiết 2)","","28",""],
["6","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 15. Luyện tập chung (Tiết 1)","2 tiết","29",""],
["6","Chủ đề 2: Bảng nhân, bảng chia","","","Bài 15. Luyện tập chung (Tiết 2)","","30",""],
["7","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 16. Điểm ở giữa, trung điểm của đoạn thẳng (Tiết 1)","2 tiết","31",""],
["7","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 16. Điểm ở giữa, trung điểm của đoạn thẳng (Tiết 2)","","32",""],
["7","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 17. Hình tròn. Tâm, bán kính, đường kính của hình tròn","1 tiết","33",""],
["7","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 18. Góc, góc vuông, góc không vuông","1 tiết","34",""],
["7","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 19. Hình tam giác, hình tứ giác, hình chữ nhật, hình vuông (Tiết 1)","3 tiết","35",""],
["8","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 19. Hình tam giác, hình tứ giác, hình chữ nhật, hình vuông (Tiết 2)","","36",""],
["8","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 19. Hình tam giác, hình tứ giác, hình chữ nhật, hình vuông (Tiết 3)","","37",""],
["8","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 20. Thực hành vẽ góc vuông, vẽ đường tròn, hình vuông, hình chữ nhật và vẽ trang trí (Tiết 1)","2 tiết","38",""],
["8","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 20. Thực hành vẽ góc vuông, vẽ đường tròn, hình vuông, hình chữ nhật và vẽ trang trí (Tiết 2)","","39",""],
["8","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 21. Khối lập phương, khối hộp chữ nhật","1 tiết","40",""],
["9","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 22. Luyện tập chung (Tiết 1)","2 tiết","41",""],
["9","Chủ đề 3: Làm quen với hình phẳng, hình khối","","","Bài 22. Luyện tập chung (Tiết 2)","","42",""],
["9","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 23. Nhân số có hai chữ số với số có một chữ số (Tiết 1)","2 tiết","43",""],
["9","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 23. Nhân số có hai chữ số với số có một chữ số (Tiết 2)","","44",""],
["9","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 24. Gấp một số lên một số lần (Tiết 1)","2 tiết","45",""],
["10","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 24. Gấp một số lên một số lần (Tiết 2)","","46",""],
["10","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 25. Phép chia hết, phép chia có dư (Tiết 1)","2 tiết","47",""],
["10","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 25. Phép chia hết, phép chia có dư (Tiết 2)","","48",""],
["10","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 26. Chia số có hai chữ số cho số có một chữ số (Tiết 1)","3 tiết","49",""],
["10","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 26. Chia số có hai chữ số cho số có một chữ số (Tiết 2)","","50",""],
["11","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 26. Chia số có hai chữ số cho số có một chữ số (Tiết 3)","","51",""],
["11","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 27. Giảm một số đi một số lần (Tiết 1)","2 tiết","52",""],
["11","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 27. Giảm một số đi một số lần (Tiết 2)","","53",""],
["11","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 28. Bài toán giải bằng hai bước tính (Tiết 1)","2 tiết","54",""],
["11","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 28. Bài toán giải bằng hai bước tính (Tiết 2)","","55",""],
["12","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 29. Luyện tập chung (Tiết 1)","2 tiết","56",""],
["12","Chủ đề 4: Phép nhân, phép chia trong phạm vi 100","","","Bài 29. Luyện tập chung (Tiết 2)","","57",""],
["12","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 30. Mi-li-mét (Tiết 1)","2 tiết","58",""],
["12","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 30. Mi-li-mét (Tiết 2)","","59",""],
["12","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 31. Gam","1 tiết","60",""],
["13","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 32. Mi-li-lít","1 tiết","61",""],
["13","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 33. Nhiệt độ. Đơn vị đo nhiệt độ","1 tiết","62",""],
["13","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 34. Thực hành và trải nghiệm với các đơn vị mi-li-mét, gam, mi-li-lít, độ C (Tiết 1)","2 tiết","63",""],
["13","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 34. Thực hành và trải nghiệm với các đơn vị mi-li-mét, gam, mi-li-lít, độ C (Tiết 2)","","64",""],
["13","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 35. Luyện tập chung (Tiết 1)","2 tiết","65",""],
["14","Chủ đề 5: Một số đơn vị đo độ dài, khối lượng, dung tích, nhiệt độ","","","Bài 35. Luyện tập chung (Tiết 2)","","66",""],
["14","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 36. Nhân số có ba chữ số với số có một chữ số (Tiết 1)","2 tiết","67",""],
["14","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 36. Nhân số có ba chữ số với số có một chữ số (Tiết 2)","","68",""],
["14","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 37. Chia số có ba chữ số cho số có một chữ số (Tiết 1)","3 tiết","69",""],
["14","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 37. Chia số có ba chữ số cho số có một chữ số (Tiết 2)","","70",""],
["15","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 37. Chia số có ba chữ số cho số có một chữ số (Tiết 3)","","71",""],
["15","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 38. Biểu thức số. Tính giá trị của biểu thức số (Tiết 1)","4 tiết","72",""],
["15","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 38. Biểu thức số. Tính giá trị của biểu thức số (Tiết 2)","","73",""],
["15","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 38. Biểu thức số. Tính giá trị của biểu thức số (Tiết 3)","","74",""],
["15","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 38. Biểu thức số. Tính giá trị của biểu thức số (Tiết 4)","","75",""],
["16","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 39. So sánh số lớn gấp mấy lần số bé (Tiết 1)","2 tiết","76",""],
["16","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 39. So sánh số lớn gấp mấy lần số bé (Tiết 2)","","77",""],
["16","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 40. Luyện tập chung (Tiết 1)","2 tiết","78",""],
["16","Chủ đề 6: Phép nhân, phép chia trong phạm vi 1 000","","","Bài 40. Luyện tập chung (Tiết 2)","","79",""],
["16","Chủ đề 7: Ôn tập học kì I","","","Bài 41. Ôn tập phép nhân, phép chia trong phạm vi 100, 1 000 (Tiết 1)","3 tiết","80",""],
["17","Chủ đề 7: Ôn tập học kì I","","","Bài 41. Ôn tập phép nhân, phép chia trong phạm vi 100, 1 000 (Tiết 2)","","81",""],
["17","Chủ đề 7: Ôn tập học kì I","","","Bài 41. Ôn tập phép nhân, phép chia trong phạm vi 100, 1 000 (Tiết 3)","","82",""],
["17","Chủ đề 7: Ôn tập học kì I","","","Bài 42. Ôn tập biểu thức số (Tiết 1)","2 tiết","83",""],
["17","Chủ đề 7: Ôn tập học kì I","","","Bài 42. Ôn tập biểu thức số (Tiết 2)","","84",""],
["17","Chủ đề 7: Ôn tập học kì I","","","Bài 43. Ôn tập hình học và đo lường (Tiết 1)","2 tiết","85",""],
["18","Chủ đề 7: Ôn tập học kì I","","","Bài 43. Ôn tập hình học và đo lường (Tiết 2)","","86",""],
["18","Chủ đề 7: Ôn tập học kì I","","","Bài 44. Ôn tập chung (Tiết 1)","2 tiết","87",""],
["18","Chủ đề 7: Ôn tập học kì I","","","Bài 44. Ôn tập chung (Tiết 2)","","88",""],
["18","Chủ đề 8: Các số đến 10 000","","","Bài 45. Các số có bốn chữ số. Số 10 000 (Tiết 1)","3 tiết","89",""],
["18","Chủ đề 8: Các số đến 10 000","","","Bài 45. Các số có bốn chữ số. Số 10 000 (Tiết 2)","","90",""],
["19","Chủ đề 8: Các số đến 10 000","","","Bài 45. Các số có bốn chữ số. Số 10 000 (Tiết 3)","","91",""],
["19","Chủ đề 8: Các số đến 10 000","","","Bài 46. So sánh các số trong phạm vi 10 000 (Tiết 1)","2 tiết","92",""],
["19","Chủ đề 8: Các số đến 10 000","","","Bài 46. So sánh các số trong phạm vi 10 000 (Tiết 2)","","93",""],
["19","Chủ đề 8: Các số đến 10 000","","","Bài 47. Làm quen với chữ số La Mã (Tiết 1)","2 tiết","94",""],
["19","Chủ đề 8: Các số đến 10 000","","","Bài 47. Làm quen với chữ số La Mã (Tiết 2)","","95",""],
["20","Chủ đề 8: Các số đến 10 000","","","Bài 48. Làm tròn số đến hàng chục, hàng trăm","1 tiết","96",""],
["20","Chủ đề 8: Các số đến 10 000","","","Bài 49. Luyện tập chung (Tiết 1)","3 tiết","97",""],
["20","Chủ đề 8: Các số đến 10 000","","","Bài 49. Luyện tập chung (Tiết 2)","","98",""],
["20","Chủ đề 8: Các số đến 10 000","","","Bài 49. Luyện tập chung (Tiết 3)","","99",""],
["20","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 50. Chu vi hình tam giác, hình tứ giác, hình chữ nhật, hình vuông (Tiết 1)","3 tiết","100",""],
["21","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 50. Chu vi hình tam giác, hình tứ giác, hình chữ nhật, hình vuông (Tiết 2)","","101",""],
["21","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 50. Chu vi hình tam giác, hình tứ giác, hình chữ nhật, hình vuông (Tiết 3)","","102",""],
["21","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 51. Diện tích của một hình. Xăng-ti-mét vuông (Tiết 1)","2 tiết","103",""],
["21","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 51. Diện tích của một hình. Xăng-ti-mét vuông (Tiết 2)","","104",""],
["21","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 52. Diện tích hình chữ nhật, diện tích hình vuông (Tiết 1)","3 tiết","105",""],
["22","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 52. Diện tích hình chữ nhật, diện tích hình vuông (Tiết 2)","","106",""],
["22","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 52. Diện tích hình chữ nhật, diện tích hình vuông (Tiết 3)","","107",""],
["22","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 53. Luyện tập chung (Tiết 1)","3 tiết","108",""],
["22","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 53. Luyện tập chung (Tiết 2)","","109",""],
["22","Chủ đề 9: Chu vi, diện tích một số hình phẳng","","","Bài 53. Luyện tập chung (Tiết 3)","","110",""],
["23","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 54. Phép cộng trong phạm vi 10 000 (Tiết 1)","2 tiết","111",""],
["23","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 54. Phép cộng trong phạm vi 10 000 (Tiết 2)","","112",""],
["23","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 55. Phép trừ trong phạm vi 10 000 (Tiết 1)","2 tiết","113",""],
["23","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 55. Phép trừ trong phạm vi 10 000 (Tiết 2)","","114",""],
["23","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 56. Nhân số có bốn chữ số với số có một chữ số (Tiết 1)","3 tiết","115",""],
["24","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 56. Nhân số có bốn chữ số với số có một chữ số (Tiết 2)","","116",""],
["24","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 56. Nhân số có bốn chữ số với số có một chữ số (Tiết 3)","","117",""],
["24","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 57. Chia số có bốn chữ số cho số có một chữ số (Tiết 1)","3 tiết","118",""],
["24","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 57. Chia số có bốn chữ số cho số có một chữ số (Tiết 2)","","119",""],
["24","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 57. Chia số có bốn chữ số cho số có một chữ số (Tiết 3)","","120",""],
["25","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 58. Luyện tập chung (Tiết 1)","3 tiết","121",""],
["25","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 58. Luyện tập chung (Tiết 2)","","122",""],
["25","Chủ đề 10: Cộng, trừ, nhân, chia trong phạm vi 10 000","","","Bài 58. Luyện tập chung (Tiết 3)","","123",""],
["25","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 59. Các số có năm chữ số. Số 100 000 (Tiết 1)","4 tiết","124",""],
["25","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 59. Các số có năm chữ số. Số 100 000 (Tiết 2)","","125",""],
["26","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 59. Các số có năm chữ số. Số 100 000 (Tiết 3)","","126",""],
["26","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 59. Các số có năm chữ số. Số 100 000 (Tiết 4)","","127",""],
["26","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 60. So sánh các số trong phạm vi 100 000 (Tiết 1)","2 tiết","128",""],
["26","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 60. So sánh các số trong phạm vi 100 000 (Tiết 2)","","129",""],
["26","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 61. Làm tròn số đến hàng nghìn, hàng chục nghìn","1 tiết","130",""],
["27","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 62. Luyện tập chung (Tiết 1)","3 tiết","131",""],
["27","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 62. Luyện tập chung (Tiết 2)","","132",""],
["27","Chủ đề 11: Các số trong phạm vi 100 000","","","Bài 62. Luyện tập chung (Tiết 3)","","133",""],
["27","Chủ đề 12: Cộng, trừ trong phạm vi 100 000","","","Bài 63. Phép cộng trong phạm vi 100 000 (Tiết 1)","2 tiết","134",""],
["27","Chủ đề 12: Cộng, trừ trong phạm vi 100 000","","","Bài 63. Phép cộng trong phạm vi 100 000 (Tiết 2)","","135",""],
["28","Chủ đề 12: Cộng, trừ trong phạm vi 100 000","","","Bài 64. Phép trừ trong phạm vi 100 000 (Tiết 1)","2 tiết","136",""],
["28","Chủ đề 12: Cộng, trừ trong phạm vi 100 000","","","Bài 64. Phép trừ trong phạm vi 100 000 (Tiết 2)","","137",""],
["28","Chủ đề 12: Cộng, trừ trong phạm vi 100 000","","","Bài 65. Luyện tập chung (Tiết 1)","2 tiết","138",""],
["28","Chủ đề 12: Cộng, trừ trong phạm vi 100 000","","","Bài 65. Luyện tập chung (Tiết 2)","","139",""],
["28","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 66. Xem đồng hồ. Tháng – năm (Tiết 1)","2 tiết","140",""],
["29","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 66. Xem đồng hồ. Tháng – năm (Tiết 2)","","141",""],
["29","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 67. Thực hành xem đồng hồ, xem lịch (Tiết 1)","2 tiết","142",""],
["29","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 67. Thực hành xem đồng hồ, xem lịch (Tiết 2)","","143",""],
["29","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 68. Tiền Việt Nam (Tiết 1)","2 tiết","144",""],
["29","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 68. Tiền Việt Nam (Tiết 2)","","145",""],
["30","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 69. Luyện tập chung (Tiết 1)","3 tiết","146",""],
["30","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 69. Luyện tập chung (Tiết 2)","","147",""],
["30","Chủ đề 13: Xem đồng hồ. Tháng – năm. Tiền Việt Nam","","","Bài 69. Luyện tập chung (Tiết 3)","","148",""],
["30","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 70. Nhân số có năm chữ số với số có một chữ số (Tiết 1)","3 tiết","149",""],
["30","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 70. Nhân số có năm chữ số với số có một chữ số (Tiết 2)","","150",""],
["31","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 70. Nhân số có năm chữ số với số có một chữ số (Tiết 3)","","151",""],
["31","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 71. Chia số có năm chữ số cho số có một chữ số (Tiết 1)","3 tiết","152",""],
["31","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 71. Chia số có năm chữ số cho số có một chữ số (Tiết 2)","","153",""],
["31","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 71. Chia số có năm chữ số cho số có một chữ số (Tiết 3)","","154",""],
["31","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 72. Luyện tập chung (Tiết 1)","2 tiết","155",""],
["32","Chủ đề 14: Nhân, chia trong phạm vi 100 000","","","Bài 72. Luyện tập chung (Tiết 2)","","156",""],
["32","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 73. Thu thập, phân loại, ghi chép số liệu. Bảng số liệu (Tiết 1)","3 tiết","157",""],
["32","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 73. Thu thập, phân loại, ghi chép số liệu. Bảng số liệu (Tiết 2)","","158",""],
["32","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 73. Thu thập, phân loại, ghi chép số liệu. Bảng số liệu (Tiết 3)","","159",""],
["32","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 74. Khả năng xảy ra của một sự kiện (Tiết 1)","2 tiết","160",""],
["33","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 74. Khả năng xảy ra của một sự kiện (Tiết 2)","","161",""],
["33","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 75. Thực hành và trải nghiệm thu thập, phân loại, ghi chép số liệu, đọc bảng số liệu (Tiết 1)","2 tiết","162",""],
["33","Chủ đề 15: Làm quen với yếu tố thống kê, xác suất","","","Bài 75. Thực hành và trải nghiệm thu thập, phân loại, ghi chép số liệu, đọc bảng số liệu (Tiết 2)","","163",""],
["33","Chủ đề 16: Ôn tập cuối năm","","","Bài 76. Ôn tập các số trong phạm vi 10 000, 100 000 (Tiết 1)","2 tiết","164",""],
["33","Chủ đề 16: Ôn tập cuối năm","","","Bài 76. Ôn tập các số trong phạm vi 10 000, 100 000 (Tiết 2)","","165",""],
["34","Chủ đề 16: Ôn tập cuối năm","","","Bài 77. Ôn tập phép cộng, phép trừ trong phạm vi 100 000 (Tiết 1)","2 tiết","166",""],
["34","Chủ đề 16: Ôn tập cuối năm","","","Bài 77. Ôn tập phép cộng, phép trừ trong phạm vi 100 000 (Tiết 2)","","167",""],
["34","Chủ đề 16: Ôn tập cuối năm","","","Bài 78. Ôn tập phép nhân, phép chia trong phạm vi 100 000 (Tiết 1)","3 tiết","168",""],
["34","Chủ đề 16: Ôn tập cuối năm","","","Bài 78. Ôn tập phép nhân, phép chia trong phạm vi 100 000 (Tiết 2)","","169",""],
["34","Chủ đề 16: Ôn tập cuối năm","","","Bài 78. Ôn tập phép nhân, phép chia trong phạm vi 100 000 (Tiết 3)","","170",""],
["35","Chủ đề 16: Ôn tập cuối năm","","","Bài 79. Ôn tập hình học và đo lường (Tiết 1)","2 tiết","171",""],
["35","Chủ đề 16: Ôn tập cuối năm","","","Bài 79. Ôn tập hình học và đo lường (Tiết 2)","","172",""],
["35","Chủ đề 16: Ôn tập cuối năm","","","Bài 80. Ôn tập bảng số liệu, khả năng xảy ra của một sự kiện","1 tiết","173",""],
["35","Chủ đề 16: Ôn tập cuối năm","","","Bài 81. Ôn tập chung (Tiết 1)","2 tiết","174",""],
["35","Chủ đề 16: Ôn tập cuối năm","","","Bài 81. Ôn tập chung (Tiết 2)","","175",""]
];
